version: '3'

services:  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # create a volume (a persistent data storage mechanism in Docker) for the database data.
    restart: always # restart the container if it stops

  stocks:
    build: 
      context: ./ # build the image from the Dockerfile in the current directory
      dockerfile: dockerfile.stocks
    container_name: stocks
    ports:
      - "5001:8000" # map port 5001 on the host to port 8000 on the container
    environment:
      - COLLECTION_NAME=collection
      - PORT=8000
      - MY_NAME=stock
    restart: always # restart the container unless it is stopped by the user
    expose:
      - 8000 # Allow other containers services to directly reach this port.
    depends_on:
      - mongo # start the mongo service before the stock-service1 service

  capital-gains-service:
    build:
      context: ./
      dockerfile: dockerfile.capital
    container_name: capital-gains-service
    ports:
      - "5003:8080"
    environment:
      - PORT=8080
    restart: always
    depends_on:
      - stocks

volumes:
  mongo_data:
    driver: local # use the local driver for the volume  


