name: assignmnt4
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # init the log.txt file
    - name: Init log file
      run: |
        START_TIME=$(date -Iminutes)
        echo "${START_TIME}" > log.txt
        echo "Yuval Shpitzer" >> log.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # # stocks image
    # - name: Build and export stocks image
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     file: ./dockerfile.stocks
    #     tags: stocks-srv:latest
    #     output: type=docker,dest=/tmp/stocks-image.tar

    # # capital-gains image
    # - name: Build and export capital-gains image
    #   uses: docker/build-push-action@v6
    #   with:
    #     context: .
    #     file: ./dockerfile.capital
    #     tags: cg-srv:latest
    #     output: type=docker,dest=/tmp/cg-image.tar

    - name: Build and export stocks image
      run: |
        set -e
        docker build -f ./dockerfile.stocks -t stocks-srv:latest .
        docker images  # Check if the image exists
        docker save stocks-srv:latest -o /tmp/stocks-image.tar || (echo "Failed to save stocks image" && exit 1)

    - name: Build and export capital-gains image
      run: |
        set -e
        docker build -f ./dockerfile.capital -t cg-srv:latest .
        docker images  # Check if the image exists
        docker save cg-srv:latest -o /tmp/cg-image.tar || (echo "Failed to save capital-gains image" && exit 1)

    - name: images status
      run: |
        ls -l /tmp
        if [ -f /tmp/stocks-image.tar ] && [ -f /tmp/cg-image.tar ]; then
          echo "Image successfully built" >> log.txt
        else
          echo "Image failed to build" >> log.txt
          exit 1
        fi

    # upload the built images and log.txt file for use in the next jobs
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: workflow-artifacts
        path: |
          log.txt
          /tmp/stocks-image.tar
          /tmp/cg-image.tar
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:

    # download the artifacts from previous jobs
    - name: Download artifacts
      uses: actions/download-artifact@v4 # download all artifacts that were uploaded

    # load the images into the docker daemon
    - name: Load images
      run: |
        docker load < workflow-artifacts/tmp/stocks-image.tar
        docker load < workflow-artifacts/tmp/cg-image.tar

    # check images are loaded
    - name: Check images
      run: docker image ls

    - name: install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Checkout
      uses: actions/checkout@v4

    - name: List files for debugging
      run: ls -la

    # start the services
    - name: Start services
      run: docker-compose up -d

    # check the services are running
    - name: Check containers
      run: |
        if [ "$(docker ps -q | wc -l)" -eq 3 ]; then
          echo "Container up and running" >> log.txt
        else
          echo "Container failed to run" >> log.txt
          exit 1
        fi

    - name: Checkout
      uses: actions/checkout@v4
      
    # set up a python environment
    - name: Set up python
      uses: actions/setup-python@v5

    # install pip, pytest, and requests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # run the tests
    - name: Run tests
      run: |
        cd tests
        pytest -v assn4_test.py > assn4_test_results.txt || true

    - name: tests results
      run: |
        if grep -q "FAILED" ./tests/assn4_test_results.txt; then
          echo "tests failed" >> log.txt
          exit 1
        else
          echo "tests succeeded" >> log.txt
        fi

    # upload the test results
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: tests/assn4_test_results.txt

  query:
    needs: build
    runs-on: ubuntu-latest
    steps:

    # download the images built in the build job
    - name: Download images
      uses: actions/download-artifact@v4 # download all artifacts that were uploaded

    # load the images into the docker daemon
    - name: Load images
      run: |
        docker load < /tmp/stocks-image.tar
        docker load < /tmp/cg-image.tar

    # check images are loaded
    - name: Check images
      run: docker image ls

    # start the services
    - name: Start services
      run: docker-compose up -d

    # check the services are running
    - name: Check services
      run: docker ps

    - name: Checkout
      uses: actions/checkout@v4
      
    # set up a python environment
    - name: Set up python
      uses: actions/setup-python@v5

    # install pip, pytest, and requests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # run the querys file
    - name: Run querys
      run: python query_services.py

    # upload the query results (response.txt) as artifact
    - name: Upload response file
      uses: actions/upload-artifact@v4
      with:
        name: query response
        path: response.txt    
