name: workf
on:
  workflow_dispatch
jobs:

  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: List all files after downloading artifacts
      run: |
        find . -name log.txt

    # init the log.txt file
    - name: Init log file
      run: |
        START_TIME=$(date -Iminutes)
        echo "${START_TIME}" > log.txt
        echo "Yuval Shpitzer" >> log.txt

    - name: Upload artifacts-build
      if: always()
      uses: actions/upload-artifact@v4

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:

    # - name: Checkout
    #   uses: actions/checkout@v4

    # download the artifacts from previous jobs
    - name: Download artifacts
      uses: actions/download-artifact@v4 # download all artifacts that were uploaded
      with:
        name: workflow-artifacts
        path: .

    - name: List all files after downloading artifacts
      run: |
        find . -name log.txt

    - name: write to log
      run: |
        echo "write in second job" >> workflow-artifacts/log.txt
        cat workflow-artifacts/log.txt

    - name: Upload-log-2
      if: always()
      uses: actions/upload-artifact@v4
